name: Continuos Integration

on: push

jobs:
  continuos-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Using Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 21.
      - name: rodando tag planets
        run: |
          npm install
          npm run test:planets
      - name: run install and test
        run: rodando tag person
          npm run test:person